### ISSUE TITLE
Use function... is not supported ?

### ISSUE THREAD

**Issue by hive-4-apps** [iCalcreator/PcGen#1]
I´m using PCGen to make a php/xml converter.
For the moment I got an error when I try 👍 `$obj_class->setUses( $a_uses );`
because I would like to add `use function path\to\my\function`
The feature is not supported yet ?
Do you think you will add it soon ?
( same question for const )

**Comment by iCalcreator** [comment]
Looking into it!

**Comment by hive-4-apps** [comment]
I did of course.
But as I´m not perfect, maube, I could not see the code where there was this feature, nobody knows.
And my last question is : do you think you will add it soon ?

**Comment by iCalcreator** [comment]
Fixed both in 1.1.47, review the releaseNotes.
Please test and verify?
